interface Project { title:string; description:string; technologies:string[]; image:string; github:string; demo?:string; }
const projects:Project[]=[
 {title:"Pointerx — AI Student Reviewer Assistant",description:"An AI-powered student reviewer assistant that serves as a study companion chatbot and converts PDFs into learning materials.",technologies:["React Native","TypeScript"],image:"/pointerx1.jpg",github:"https://github.com/flinch2017/Pointerx"},
 {title:"Fruityger — Social Media Platform",description:"A social networking platform built with React, JavaScript, and Supabase.",technologies:["React","JavaScript","Node.js","Supabase"],image:"/fruityger1.png",github:"https://github.com/flinch2017/fruityger",demo:"https://fruityger.onrender.com"},
 {title:"Fruityger Mobile — Social Platform",description:"A React Native version of Fruityger featuring messaging, notifications, posts, and an engaging mobile experience.",technologies:["React Native","Expo","TypeScript"],image:"/fruitygerapp1.jpg",github:"https://github.com/flinch2017/FruitygerMobile"},
 {title:"Barangay Profiling System",description:"A resident profiling and certificate management system for community records and local officials.",technologies:["React","Node.js","Supabase","Cloudflare R2"],image:"/bps1.png",github:"https://github.com/flinch2017/barangay-profiling-system"},
];
function Projects(){return <section id="projects"><div className="section-inner"><div className="section-heading"><div><span className="eyebrow">Selected work</span><h2 className="section-title">Products designed to solve real problems.</h2></div><p className="section-intro">A selection of independent projects spanning education, community systems, and social platforms.</p></div><div className="projects-grid">{projects.map((project,index)=><article className="project-card" key={project.title}><div className="project-image" style={{backgroundImage:`url(${project.image})`}}/><div className="project-content"><span className="project-kicker">Case study / 0{index+1}</span><h3>{project.title}</h3><p>{project.description}</p><div className="project-tech">{project.technologies.map(tech=><span key={tech}>{tech}</span>)}</div><div className="project-links"><a href={project.github} target="_blank" rel="noreferrer">GitHub ↗</a>{project.demo&&<a href={project.demo} target="_blank" rel="noreferrer">Live demo ↗</a>}</div></div></article>)}</div></div></section>}
export default Projects;
